### ISSUE TITLE
巨炽焰的+120速度不生效

### ISSUE THREAD

**Issue by Weiyi122332** [CallmeSHaobe/123Technology#10]
![PixPin_2024-09-26_19-29-52](https://github.com/user-attachments/assets/79c06f6b-8d99-4541-aab7-8026d9eaa282)

![PixPin_2024-09-26_19-30-19](https://github.com/user-attachments/assets/62cfd713-fb7f-4619-90b9-3d7490455523)

**Comment by Weiyi122332** [comment]
刚刚算了一下，能源90%也没完全生效

**Comment by CallmeSHaobe** [comment]
随后在新release中修复
