### ISSUE TITLE
maple的温馨小提示

### ISSUE THREAD

**Issue by maple-9945** [CallmeSHaobe/123Technology#11]
1：红日之恩情将军配件厂除巨型PCB外其他类型配方无法运行。
2：红日之恩情将军配件厂可制作阶段时贴片工坊产出的封装贴片大多数无用，建议拆分（刚刚审视了一下，没有tst的话很不错，有了tst之后就有点鸡肋了，所以不管也成）。
3：为艾莎锻炉添加通用SOC制作光学处理器的配方。（老登不想用奇迹顶点的高级光学处理器配方，目前看来存在配方循环，所以亲爱的小蓝狗会加的吧！）

**Comment by CallmeSHaobe** [comment]
biebie
