### ISSUE TITLE
模组若干问题

### ISSUE THREAD

**Issue by Wy9Aready** [CallmeSHaobe/123Technology#13]
红日恩情配件厂的元件聚合者模式存在有重复配方，以及NMD晶圆厂存在产物够但是不工作问题（以输入恩情），狄拉克在执行被动产线时候注视主机容易卡死。

**Comment by Wy9Aready** [comment]
后续模组更新能不能加上钢叶等难获取配方。

**Comment by CallmeSHaobe** [comment]
憋憋以后会加的

**Comment by Wy9Aready** [comment]
憋憋别以后加了，132就加吧
