### ISSUE TITLE
增加一些新的蜜蜂

### ISSUE THREAD

**Issue by JustAlkaid** [CallmeSHaobe/123Technology#17]
| 蜜蜂名 | 父本母本 | 杂交要求 | 用途 |
|---|---|---|---|
| 玻璃蜂 | 粘土蜂，田园蜂 | 基座：通透玻璃 | 蜂窝离心 25% 产出 1 个蜂蜜滴，100% 产出 1 个玻璃。 |
| 海珀珍蜂 | 无尽蜂，龙血蜂 | 基座：部件装配线外壳(UIV) | 1. 在 DTPF 中为所有产出海珀珍的配方增产 100%，每次消耗 1 个海珀珍蜂窝。<br>2. 在 DTPF 产量子合金的配方中，取代配方输入的海珀珍。每个海珀珍蜂窝替代 2304L 熔融海珀珍。 |
| 彩色玻璃蜂 | 无尽蜂，玻璃蜂 | 基座：彩色玻璃块 | 1. 在 DTPF 中为所有产出彩色玻璃的配方执行一次无损超频，每次消耗 4 个彩色玻璃蜂窝。<br>2. 为激光蚀刻机产彩色玻璃粉的配方执行一次无损超频。消耗 1 个彩色玻璃蜂窝。 |

**Comment by CallmeSHaobe** [comment]
done
