### ISSUE TITLE
唐山炼钢厂处理部分配方耗时错误

### ISSUE THREAD

**Issue by Hatoric** [CallmeSHaobe/123Technology#5]
1.处理配方耗时错误。
2.处理配方时，会一次性消耗所有输入的物品并大幅增加耗时。下两图电力输入没变化，材料输入翻了约百倍，产出效率却变成了一半
![(J)9Q O_}%MBGB6J%YBQZ(K](https://github.com/user-attachments/assets/b890d0fc-e8c8-4c11-82ad-5d3f18c38bbf)
![1Z6QS~2VEDXY1 C U3OB 32](https://github.com/user-attachments/assets/f825eb24-1ce6-4def-80ec-8eb737fd0174)

**Comment by CallmeSHaobe** [comment]
新release已发布，憋憋。

**Comment by CallmeSHaobe** [comment]
坏了。重写的机制问题更大了。预计明天加入无线电网功能。

**Comment by CallmeSHaobe** [comment]
无线了
